# Generated by Django 4.2 on 2023-08-04 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='expected_deliveryDate',
            field=models.DateField(default=datetime.date(2023, 8, 11)),
        ),
    ]
