# Generated by Django 4.2 on 2023-08-12 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_orders_expected_deliverydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='expected_deliveryDate',
            field=models.DateField(default=datetime.date(2023, 8, 19)),
        ),
    ]
